disabled_rules:
  - block_based_kvo # swift 3.2
  - force_cast
opt_in_rules:
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
line_length: 240
type_body_length:
  - 400 # error
file_length:
  warning: 600
  error: 1200
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)