osx_image: xcode10.2
language: swift
env:
  global:
    - WORKSPACE=BitmarkRegistry.xcworkspace
    - SCHEME=BitmarkRegistry
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.2,name=iPhone X"    SCHEME="BitmarkRegistry"      RUN_TESTS="NO"  RUN_DANGER="YES"
    - DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone 7"    SCHEME="BitmarkRegistry"      RUN_TESTS="NO"  RUN_DANGER="NO"
cache:
  directories:
    - Pods
    - ~/.danger-swift
addons:
  homebrew:
    update: true
    taps:
      - danger/tap
    packages:
      - carthage
      - danger-swift
      - swiftlint

before_install:
  - pod install

script:
  - swiftlint
  - set -o pipefail

  # Build Framework and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty;
    else
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run Danger if specified
  - if [ $RUN_DANGER == "YES" ]; then
      DEBUG='*' danger-swift ci;
    fi