osx_image: xcode10.2
language: swift
env:
  global:
    - WORKSPACE=BitmarkRegistry.xcworkspace
  matrix:
    - LINTONLY="YES"
    - DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone X"    SCHEME="BitmarkRegistry"      LINTONLY="NO"
    - DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone X"    SCHEME="BitmarkRegistry Dev"  LINTONLY="NO"
cache:
  cocoapods: true
addons:
  homebrew:
    packages:
      - swiftlint

install:
  - pod install --repo-update
  - gem install xcpretty-travis-formatter

script:
  - if [ $LINTONLY == "YES" ]; then
      swiftlint lint --config .swiftlint-ci.yml;
    else
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`;
    fi
